version: 0.2
phases:
  install:
    runtime-versions:
      python: 3.11
    commands:
      - apt-get update
      - apt-get install -y python3-pip
      - pip3 install --upgrade pip
      - pip3 install -r requirements.txt
  build:
    commands:
      - echo Prebuild ops
#      - pip3 install -r requirements.txt
  post_build:
    commands:
      - echo Build completed on `date`
artifacts:
  files:
    - '**/*'
